// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © yoooounglee

//@version=6

indicator("RSI", shorttitle="RSI", overlay=false)

// RSI 参数设置
len = input.int(14, "RSI Length", group = "RSI")  // RSI 的计算周期长度

// RSI 阈值设置
upper_ = input.int(70, "Threshold: ⭱", inline = "Threshold")  // RSI 上限阈值
lower_ = input.int(30, " ⤓", inline = "Threshold")           // RSI 下限阈值


// 计算 RSI 值
rsi = ta.rsi(close, len)


// --------------------------------------------------------------------------------------------------------------------}
// 可视化部分
// --------------------------------------------------------------------------------------------------------------------{

// 绘制 RSI 线
rsiPlot = plot(rsi, "RSI", color=chart.fg_color)

// 绘制 RSI 上下限水平线
rsiUpperBand = hline(upper_, "RSI Upper Band", color=#787B86)
midline = hline(50, "RSI Middle Band", color=color.new(#787B86, 50))
rsiLowerBand = hline(lower_, "RSI Lower Band", color=#787B86)

// 填充 RSI 背景
fill(rsiUpperBand, rsiLowerBand, color=#c292571a, title="RSI Background Fill")

